# Generated by Django 4.0.7 on 2023-03-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_ip', models.GenericIPAddressField(null=True, unique=True)),
                ('device_alias', models.CharField(default='-/-', max_length=128, null=True)),
                ('net_area', models.CharField(default='-/-', max_length=32, null=True)),
                ('device_type', models.CharField(default='-/-', max_length=32, null=True)),
                ('device_model', models.CharField(default='-/-', max_length=32, null=True)),
                ('device_version', models.CharField(default='-/-', max_length=64, null=True)),
                ('device_sn', models.CharField(default='-/-', max_length=32, null=True)),
                ('community_data', models.CharField(default='-/-', max_length=32, null=True)),
                ('device_uptime', models.CharField(default='-/-', max_length=64, null=True)),
                ('device_cpu', models.IntegerField(null=True)),
                ('device_mem', models.IntegerField(null=True)),
                ('device_power_state', models.IntegerField(null=True)),
                ('device_fan_state', models.IntegerField(null=True)),
                ('device_temperature', models.IntegerField(null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('last_sync_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_location', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snmp_state', models.BooleanField()),
                ('icmp_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(default='New Device', max_length=64, null=True)),
                ('mgmt_ip', models.GenericIPAddressField(null=True, unique=True)),
                ('device_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='device_app.devicedetail')),
                ('device_location', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='device_app.devicelocation')),
                ('device_state', models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='device_app.devicestate')),
            ],
        ),
    ]
