# Generated by Django 4.0.7 on 2023-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, null=True, unique=True)),
                ('task_type', models.CharField(default='SNMP同步', max_length=32, null=True)),
                ('scheduler_type', models.CharField(default='手动', max_length=32, null=True)),
                ('task_state', models.CharField(default='执行中', max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('exec_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
